### ISSUE TITLE
Forcefully Enable TLS 1.2 with cURL PHP

### ISSUE THREAD

**Issue by alenmjis** [razorpay/razorpay-woocommerce#88]
Is there any way to forcefully enable TLS 1.2 with cURL PHP? 

(Our Windows hosting supports TLS 1.2 but doesn't forcefully enable that - And the system is below .NET 4 )

**Comment by captn3m0** [comment]
Since this plugin uses https://github.com/razorpay/razorpay-php/issues/81 internally, I've filed a issue there: https://github.com/razorpay/razorpay-php/issues/81

The fix itself should be simple (PRs are welcome) - A request hook on curl.before that forces TLS1.2

Leaving this open since the changes will have to be merged back here.

**Comment by captn3m0** [comment]
The SDK is upgraded already, this requires a version bump on the plugin end: https://github.com/razorpay/razorpay-woocommerce/issues/109
